server:
  port: 8082

spring:
  application:
    name: eureka-client-order
eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/