server:
  port: 8761
spring:
  application:
    name: EurekaServer
  security:
    user:
      name: user
      password: password123

eureka:
  instance:
    hostname: localhost
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/,http://user:password123@localhost:8762/eureka/
    registry-fetch-interval-seconds: 10