server:
  port: 8082

spring:
  application:
    name: order
  cloud:
    consul:
      host: 192.168.3.223
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${server.port}
        health-check-interval: 10s
        health-check-headers:
          X-Config-Token: 6442e58b-d1ea-182e-cfa5-cf9cddef0722
        health-check-url: http://192.168.3.214:8082/
        tags: foo=bar, baz=1